### ISSUE TITLE
'R' Train Data 

### ISSUE THREAD

**Issue by Asher978** [aamaliaa/mta-gtfs#10]
Is there a bug retrieving the data for the R line or is it due to MTA not providing the data? I made few queries with no response on the R line stations. 

Thanks

**Comment by panicpanicpanic** [comment]
Hey @Asher978 what stop were you trying to request data for? I have experienced some issues with requesting data from lines that are in Beta.

**Comment by Asher978** [comment]
In specific it was the 'R' train. Response kept coming empty for any of 'R' train Stops. I am thinking it probably is the MTA feed not an error on this API. But i would like clarification so i can move forward.

**Comment by steveraaen** [comment]
For me, R train data is in sync with the overhead boards .
