### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by cagosto** [aamaliaa/mta-gtfs#11]
Hi I add my MTA API key but I get an error 

1. Failed to load http://web.mta.info/status/serviceStatus.txt: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

I didn't see anything in your read me about passing headers just wondering if you have come across this issue.

**Comment by aamaliaa** [comment]
Hi @cagosto! Are you using this in client-side js instead of node.js? The library is intended for use in node.js server code. See https://github.com/aamaliaa/mta-gtfs/issues/6. Hope that helps!
