### ISSUE TITLE
Example code returns "No 'Access-Control-Allow-Origin' header is present on the requested resource"

### ISSUE THREAD

**Issue by dance2die** [aamaliaa/mta-gtfs#6]
Hi Amalia.

As I am running this example code,

        this.mta.status('subway').then((result) => {
            console.log(result);
        });

I am getting a following error message.

> XMLHttpRequest cannot load http://web.mta.info/status/serviceStatus.txt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

Is that the problem with the library or is it because MTA didn't enable CORS?

Here is the full source (website is created using `create-react-app`) of the example as a context.

```javascript
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

import apiKeys from './apiKeys';
import Mta from 'mta-gtfs';

class App extends Component {
    constructor(props) {
        super(props);

        debugger;

        this.mta = new Mta({
            key: apiKeys.MTA_API_KEY,
            feed_id: 1                  // optional, default = 1
        });

        this.state = {};
    }

    componentDidMount() {
        this.mta.status('subway').then((result) => {
            console.log(result);
        });
    }

    render() {
        return (
            <div className="App">
            </div>
        );
    }
}

export default App;

```

**Comment by aamaliaa** [comment]
Hi @dance2die, thanks for checking out the library. It is intended to be used on a server and not the client/browser (node.js only). If you have a node.js backend in your app, you can use mta-gtfs there and expose the data through API endpoints--this way you won't run into any cross-origin issues via the client.

**Comment by dance2die** [comment]
I haven't used Node.js before so it sounds interesting.

And thank you again @aamaliaa for sharing the code with MIT license so that I can fork the code to `fetch` data via YQL (to get around CORS restriction).
